### PR TITLE
Rename 527K to Purifier Hot+Cool Formaldehyde

### PR DESCRIPTION
**Pull request by x86-39**
This pull request renames the 527K, currently named "Purifier Hot+Cool" to "Purifier Hot+Cool Formaldehyde". I have this model of fan and it also includes Formaldehyde readings and filter, so I assume this name was used for this model number in error. It includes the formaldehyde reading in the same was as the "Purifier Humidify+Cool Formaldehyde" device does it.

### CODE REVIEW

**Comment by x86-39** [comment]
Let me update the tests one second

**Comment by dotvezz** [comment]
Hi @diademiemi! It's _awesome_ to see people raising pull requests! Thanks so much!

Properly supporting Formaldehyde models actually happens to be one of the things I want to solve with a light refactor I'm working on right now. The challenge here is this: Dyson dealt us a tricky hand with their product codes for Formaldehyde models. The code `527K` is correct for **_BOTH_** the Formaldehyde and non-Formaldehyde Purifier Hot+Cool. It's the same for _all_ the Formaldehyde models, including the Humidifier; they all have product code collisions with their basic counterparts.

I'm working on a couple of ideas to resolve this:

- API Based resolution: Find a new API endpoint that gives the info? A pure API-based approach using the currently used endpoints is impossible because there's no deterministic distinguishing factor between Formaldehyde and "normal" Purifier Hot+Cool models.
  - The API has a `name` field that _can_ identify Formaldehyde models. Unfortunately, it's not reliable for our purposes as it can be edited by users in the mobile app.
  - I've been reverse-engineering the API for fixing the cloud login issues and will continue to see if there's an API we can use to identify Formaldehyde models. 
- Sensor interview resolution? We could add an "Interview" functionality (and add it as a setup step to the `ha-dyson` local integration) that uses sensor data to determine whether it's a Formaldehyde model or not.

I'd love to hear if you or anyone else has more thoughts though!

**Comment by x86-39** [comment]
Ahh right, my bad, I didn't realise! I saw a pull request on the original repo which also had the 527K as this model so I assumed this one was wrong, so I sent in this PR.

I think keeping the functionality to resolve it local would be better. I'd prefer for it to try to poll for formaldehyde to check it's capabilities instead of an API endpoint.

**Comment by dotvezz** [comment]
I'd prefer to do it locally, but the API path seems valid too (if it's even possible to get the info we need). That's because (I believe) the Formaldehyde models can _only_ be setup using the cloud API functionality anyway. To my knowledge, they don't ship with the credentials sticker that allows offline setup for older models like HP04. So while I'd prefer a local-only interview, if the API path is significantly easier then I'll probably go that way.

Of course, now I should ask you: Did your HP09 ship with the wifi access sticker that lets you generate credentials locally?

**Comment by x86-39** [comment]
My bad I missed this notification.

Yes indeed mine did not ship with a wifi access sticker or any other way to set it up, I did have to use the app. 

After using the app I set it up with this integration and placed it in a subnet that is not allowed internet access and it still does work perfectly, so aside from the initial setup it does not need an active connection. So yeah if the online path is easier it wouldn't be a big problem

**Comment by dotvezz** [comment]
Well, v1.0.0 is released with support for all Formaldehyde devices! It adds a `formaldehyde` property to all Fan devices, which returns `None`. This isn't intended to be a permanent solution; ultimately, I want to be able to make the prop more ergonomic to use, but it works for now!

It's a v1 release because of breaking changes: renaming a lot of consts and deleting a Formaldehyde-related class.

I've also released v0.18.0 of the dyson-local integration which now supports Formaldehyde devices. If `formaldehyde is None` then it simply doesn't register a Formaldehyde sensor in Home Assistant.

One note, I've been testing with a _simulated_ device as my 527K happens to be the no-Formaldehyde version. Please feel free to install and test. There should be no breaking changes to dyson-local, but please let me know if you experience any problems.

**Pull request closed without merging**
