### PR TITLE
for Support PURIFIER_HUMIDIFY_COOL_FORMALDEHYDE 358K

### PR DESCRIPTION
**Pull request by WonchulKang**
fix for support model name 358K

### CODE REVIEW

**Review by mtjweb — APPROVED** [review]

**Review by mtjweb — APPROVED** [review]

**Comment by dotvezz** [comment]
Hi @WonchulKang! It's really exciting to see people raising pull requests here. 정말로 고맙네요.

Support for Formaldehyde models is an important goal for the coming couple of weeks. Feel free to read a bit more in a related comment on this other pull request: https://github.com/libdyson-wg/libdyson-neon/pull/7#issuecomment-1501923127. TL;DR: There's an issue with product codes that I am trying to resolve.

For that reason, I actually have one request for you to help me catalog the information for the Formaldehyde products. If you own this model, could you please show the output of running `get_devices.py`?

(만약 영어 쓰는 게 불편하시다면 한글로 쓰셔도 좋습니다)

**Comment by mtjweb** [comment]
The output for my three Dyson Purifier Humidify+Cool Formaldehyde is:

Serial: X0X-EU-XXX0000X
Name: Huiskamer
Device Type: 358E
Credential: KCogcFqnobsIu7VudCwRG2ta0BvUZHn2ZrP3yitIW4PB6Xzo/zfivI0/+Ld+PFH7EyKpdwKeouOKIMwXLNcSmg==

Serial: X0X-EU-XXX0000X
Name: Kantoor
Device Type: 358K
Credential: TmJa1kJNnej/WWtgn1Qe0UP6CZ1fKlXcyX3+D56csK/L7/wmbTlPVXJNVaA6wFqa/eg8VSFQ411321Ws8YTtqQ==

Serial: X0X-EU-XXX0000X
Name: Slaapkamer
Device Type: 358K
Credential: F4kFZGOIQK74XV+xR0Sv4dhBarW2Cfu2WjkHLEbWnxejYhuwvlX+xIBsQdUYFkIQH77eKlwasrMVUjuwb4o6ZQ==

**Comment by dotvezz** [comment]
@mtjweb interesting, thanks! I wish I could figure out some consistent pattern around the `K` and `E` designations in the product codes. I realize this may be asking for too much information, and I fully understand if you don't feel comfortable sharing, but would you be able to share receipts and/or serial numbers for those? Were all three sold under the "PH04" model designation?

I'm really just hoping to find some kind of rhyme or reason that explains which devices get which product code if they're sold with the exact same model name.

**Comment by mtjweb** [comment]
@dotvezz, I have checked the labels on the bottom of the devices and see the following:

The type 358K has the modelnumber "PH04 YY" and both serialnumbers begin with X6P-EU-..
The type 358E has the modelnumber "PH04" and the serialnumber begins with M9F-EU-..

Other than that I don't see any differences in the models.

**Comment by dotvezz** [comment]
Thanks @mtjweb, really appreciate the info. The `YY` part of the model number and the common serial number prefix for the K's are interesting. Maybe there's something there?

For now, I'm not sure it's worthwhile to collect serial numbers on a large scale, but at least it's a possible avenue to follow if the other options don't pan out.

**Comment by DarkoKukovec** [comment]
Hi, just adding one more data point here... (from `get_devices.py`)

PH04 YY (Formaldehyde)
Device type: 358K
Serial number: X6P-EU-...

**Comment by WonchulKang** [comment]
sorry for replying late
here is my Dyson Purifier Humidify+Cool Formaldehyde info

Serial: X6D-KR-....
Name: 안방
Device Type: 358K
Credential: ...

**Comment by dotvezz** [comment]
v1.0.0 is released with support for all Formaldehyde devices! It adds a `formaldehyde` property to all Fan devices, which returns `None`. This isn't intended to be a permanent solution; ultimately, I want to be able to make the prop more ergonomic to use, but it works for now!

It's a v1 release because of breaking changes: renaming a lot of consts and deleting a Formaldehyde-related class.

I've also released v0.18.0 of the dyson-local integration which now supports Formaldehyde devices. If `formaldehyde is None` then it simply doesn't register a Formaldehyde sensor in Home Assistant.

One note, I've been testing with a _simulated_ device because my 527K happens to be the no-Formaldehyde version. Please feel free to install and test. There should be no breaking changes to dyson-local, but please let me know if you experience any problems.

**Pull request closed without merging**
